### ISSUE TITLE
Connection to local service bus refused by peer

### ISSUE THREAD

**Issue by genieplus** [Azure/azure-service-bus-samples#2]
Hi, 
I updated the examples in the proton-c-queues-and-topics directory and tried to connect to my local service bus. 
```cpp
SNPRINTF(address, sizeof(address), "amqps://%s:%s@%s/%s/%s", issuerName, key, host, sbnamespace, entity);
```

Unfortunately, it fails with the following message error

    Sending messages to amqps://issuerName:issuerKey@my-server/ServiceBusDefaultNamespace/q1
    CALL pn_messenger_set_outgoing_window... RETURNED 0
    CALL pn_messenger_set_blocking... RETURNED 0
    CALL pn_messenger_start... RETURNED 0
    CALL pn_messenger_put... RETURNED 0
    CALL pn_messenger_send... recv: Connection reset by peer
    [0x1449a80]:ERROR amqp:connection:framing-error SSL Failure: Unknown error.
    CONNECTION ERROR connection aborted (remote)
    RETURNED 0

I checked the network logs, the SSL connection was established correctly and I could see that AMQP version message have be exchanged between two peers.

Any idea?

**Comment by JamesBirdsall** [comment]
I suspect the SSL framing error is because the connection was closed abruptly for other reasons. If you're using Service Bus Server, then the only authentication mode which Proton-C is Windows auth, meaning the issuerName is the Windows username, and key is the Windows password. pn_messenger_send() is when an auth error would show up, because SB can't perform authorization until the AMQP link is created, because until then it doesn't know what entity to perform the check against.

**Comment by genieplus** [comment]
I tried a local account. The issue remains the same : (
